pull_request_rules:

  # --- CI labels --- #
  - name: Set needs-ci label
    conditions:
      - or:
        # Build test
        - -check-success=build (gcc, 10)
        - -check-success=build (gcc, 11)
        - -check-success=build (clang, 10)
        - -check-success=build (clang, 11)
        - -check-success=build (clang, 12)
        # Unit tests
        - -check-success=build (GCC)
        - -check-success=build (GCC_ASAN_UBSAN)
        - -check-success=build (CLANG)
        - -check-success=build (CLANG_ASAN_UBSAN)
        # CentOS CI
        - -check-success=CentOS CI (CentOS 8)
        # LGTM
        - "-check-success=LGTM analysis: JavaScript"
        - "-check-success=LGTM analysis: Python"
        - "-check-success=LGTM analysis: C/C++"
        # Packit
        - -check-success=packit/rpm-build-fedora-34-aarch64
        - -check-success=packit/rpm-build-fedora-34-x86_64
    actions:
      label:
        add:
          - needs-ci

  - name: Remove needs-ci label
    conditions:
      # Build test
      - check-success=build (gcc, 10)
      - check-success=build (gcc, 11)
      - check-success=build (clang, 10)
      - check-success=build (clang, 11)
      - check-success=build (clang, 12)
      # Unit tests
      - check-success=build (GCC)
      - check-success=build (GCC_ASAN_UBSAN)
      - check-success=build (CLANG)
      - check-success=build (CLANG_ASAN_UBSAN)
      # CentOS CI
      - check-success=CentOS CI (CentOS 8)
      # LGTM
      - "check-success=LGTM analysis: JavaScript"
      - "check-success=LGTM analysis: Python"
      - "check-success=LGTM analysis: C/C++"
      # Packit
      - check-success=packit/rpm-build-fedora-34-aarch64
      - check-success=packit/rpm-build-fedora-34-x86_64
    actions:
      label:
        remove:
          - needs-ci


  # --- Review labels --- #
  - name: Set needs-review label
    conditions:
      - or:
        - "-#approved-reviews-by>=1"
        - "-#review-requested=0"
        - "-#changes-requested-reviews-by=0"
    actions:
      label:
        add:
          - needs-ci
          
  - name: Remove needs-review label
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      label:
        remove:
          - needs-ci

  
  # --- Plumber labels --- #
  # TODO: somehow sync with Plumber
  
  
  # --- Branch labels --- #
  # - RHEL 9.0.0-beta - #
  - name: Set rhel-9.0.0-beta label
    conditions:
      - base=rhel-9.0.0-beta
    actions:
      label:
        add:
          - rhel-9.0.0-beta
        
  - name: Remove rhel-9.0.0-beta label
    conditions:
      - base!=rhel-9.0.0-beta
    actions:
      label:
        remove:
          - rhel-9.0.0-beta
        
  # - RHEL 9.0.0 - #
  - name: Set rhel-9.0.0 label
    conditions:
      - base=rhel-9.0.0
    actions:
      label:
        add:
          - rhel-9.0.0
        
  - name: Remove rhel-9.0.0 label
    conditions:
      - base!=rhel-9.0.0
    actions:
      label:
        remove:
          - rhel-9.0.0 
    
  # - RHEL 9.1.0 - #
  - name: Set rhel-9.1.0 label
    conditions:
      - base=rhel-9.1.0
    actions:
      label:
        add:
          - rhel-9.1.0
        
  - name: Remove rhel-9.1.0 label
    conditions:
      - base!=rhel-9.1.0
    actions:
      label:
        remove:
          - rhel-9.1.0
    
  # - RHEL 9.2.0 - #
  - name: Set rhel-9.2.0 label
    conditions:
      - base=rhel-9.2.0
    actions:
      label:
        add:
          - rhel-9.2.0
        
  - name: Remove rhel-9.2.0 label
    conditions:
      - base!=rhel-9.2.0
    actions:
      label:
        remove:
          - rhel-9.2.0
    
  # - RHEL 9.3.0 - #
  - name: Set rhel-9.3.0 label
    conditions:
      - base=rhel-9.3.0
    actions:
      label:
        add:
          - rhel-9.3.0
        
  - name: Remove rhel-9.3.0 label
    conditions:
      - base!=rhel-9.3.0
    actions:
      label:
        remove:
          - rhel-9.3.0
    
  # - RHEL 9.4.0 - #
  - name: Set rhel-9.4.0 label
    conditions:
      - base=rhel-9.4.0
    actions:
      label:
        add:
          - rhel-9.4.0
        
  - name: Remove rhel-9.4.0 label
    conditions:
      - base!=rhel-9.4.0
    actions:
      label:
        remove:
          - rhel-9.4.0
    
  # - RHEL 9.5.0 - #
  - name: Set rhel-9.5.0 label
    conditions:
      - base=rhel-9.5.0
    actions:
      label:
        add:
          - rhel-9.5.0
        
  - name: Remove rhel-9.5.0 label
    conditions:
      - base!=rhel-9.5.0
    actions:
      label:
        remove:
          - rhel-9.5.0
    
  # - RHEL 9.6.0 - #
  - name: Set rhel-9.6.0 label
    conditions:
      - base=rhel-9.6.0
    actions:
      label:
        add:
          - rhel-9.6.0
        
  - name: Remove rhel-9.6.0 label
    conditions:
      - base!=rhel-9.6.0
    actions:
      label:
        remove:
          - rhel-9.6.0
    
  # - RHEL 9.7.0 - #
  - name: Set rhel-9.7.0 label
    conditions:
      - base=rhel-9.7.0
    actions:
      label:
        add:
          - rhel-9.7.0
        
  - name: Remove rhel-9.7.0 label
    conditions:
      - base!=rhel-9.7.0
    actions:
      label:
        remove:
          - rhel-9.7.0
    
  # - RHEL 9.8.0 - #
  - name: Set rhel-9.8.0 label
    conditions:
      - base=rhel-9.8.0
    actions:
      label:
        add:
          - rhel-9.8.0
        
  - name: Remove rhel-9.8.0 label
    conditions:
      - base!=rhel-9.8.0
    actions:
      label:
        remove:
          - rhel-9.8.0
    
  # - RHEL 9.9.0 - #
  - name: Set rhel-9.9.0 label
    conditions:
      - base=rhel-9.9.0
    actions:
      label:
        add:
          - rhel-9.9.0
        
  - name: Remove rhel-9.9.0 label
    conditions:
      - base!=rhel-9.9.0
    actions:
      label:
        remove:
          - rhel-9.9.0
        
  # TODO: labels and backports (rhel-9.0.0, rhel-9.1.0, ...)
  
  
  # --- Merge rules --- #
  - name: Automatic merge on approval
    conditions:
      - and:
        # Check for draft PR and WIP in title
        - -draft
        - -title~=(?i)wip
        # ~needs-review && ~needs-acks && ~needs-bz && ~dont-merge && ( ~needs-ci || ( needs-ci && ci-waived ))
        - label!=needs-review
        - label!=needs-acks
        - label!=needs-bz
        - label!=dont-merge
        - or:
          - label!=needs-ci
          - and:
            - label=needs-ci
            - label=ci-waived
    actions:
      merge:
        method: merge
